# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1krtu_0QIsMTMFEsln0tU38JkTbovSNKi
"""

pip install langchain-community pypdf

"""Loading documents"""

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader('/content/SamplePDF-40kb-Text-7pages.pdf')
docs = loader.load()
print(len(docs))

print(docs[0].page_content)
print(docs[1].metadata)

"""Splitting"""

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000, chunk_overlap=200, add_start_index=True
)
all_splits = text_splitter.split_documents(docs)

print(len(all_splits))

"""Embeddings"""

pip install -qU langchain-huggingface

from langchain_huggingface import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")

vector_1 = embeddings.embed_query(all_splits[0].page_content)
vector_2 = embeddings.embed_query(all_splits[1].page_content)

assert len(vector_1) == len(vector_2)
print(f"Generated vectors of length {len(vector_1)}\n")
print(vector_1[:10])

"""Vector stores"""

pip install -qU langchain-community faiss-cpu

import faiss
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_community.vectorstores import FAISS

embedding_dim = len(embeddings.embed_query("hello world"))
index = faiss.IndexFlatL2(embedding_dim)

vector_store = FAISS(
    embedding_function=embeddings,
    index=index,
    docstore=InMemoryDocstore(),
    index_to_docstore_id={},
)

ids = vector_store.add_documents(documents=all_splits)

results = vector_store.similarity_search(
    """Fifty years ago or more, you would have been likely enough any fine
morning to catch"""
)

print(results[0])

# Note that providers implement different scores; the score here
# is a distance metric that varies inversely with similarity.

results = vector_store.similarity_search_with_score("""Fifty years ago or more, you would have been likely enough any fine
morning to catch""")
doc, score = results[0]
print(f"Score: {score}\n")
print(doc)

"""Return documents based on similarity to an embedded query"""

embedding = embeddings.embed_query("""how many years ago you would have been likely enough any fine
morning to catch""")

results = vector_store.similarity_search_by_vector(embedding)
print(results[0])

"""Retrivers"""

from typing import List

from langchain_core.documents import Document
from langchain_core.runnables import chain


@chain
def retriever(query: str) -> List[Document]:
    return vector_store.similarity_search(query, k=1)


retriever.batch(
    [
        """Where did Eileen Fitzmaurice, six or seven years old,had
lived with her mother and aunt?""",
        "Where is House in Glendoula",
    ],
)

