# -*- coding: utf-8 -*-
"""README.md

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S5764ta3VASx01m7vpY-niI5LpJeP_Cg
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile README.md
# # PDF Q&A RAG App
# 
# Upload a PDF and ask questions using an LLM.
# 
# Technologies:
# - LangChain
# - Streamlit
# - Hugging Face
# - Chroma vector database

