# -*- coding: utf-8 -*-
"""requirements.txt

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LDb9gzcgQ7LtnfSed2VrEpaQqNu-O7jO
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# langchain
# langchain-community
# chromadb
# sentence-transformers
# huggingface_hub
# pypdf

