# -*- coding: utf-8 -*-
"""Untitled80.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hl5Plt9yCJoTM1s29Bby5kKv5PS2irrD
"""

import streamlit as st
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.docstore.in_memory import InMemoryDocstore
from langchain_community.vectorstores import FAISS

st.title("PDF Q&A RAG App")

# Upload PDF
uploaded_file = st.file_uploader("Upload a PDF", type="pdf")

if uploaded_file:
    # Load PDF
    loader = PyPDFLoader(uploaded_file)
    docs = loader.load()

    st.write(f"Loaded {len(docs)} pages")

    # Split text
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000, chunk_overlap=200, add_start_index=True
    )
    all_splits = text_splitter.split_documents(docs)

    st.write(f"Split into {len(all_splits)} chunks")

    # Embeddings
    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-mpnet-base-v2"
    )

    # Vector store
    import faiss
    embedding_dim = len(embeddings.embed_query("hello world"))
    index = faiss.IndexFlatL2(embedding_dim)

    vector_store = FAISS(
        embedding_function=embeddings,
        index=index,
        docstore=InMemoryDocstore(),
        index_to_docstore_id={},
    )

    vector_store.add_documents(all_splits)

    # Ask question
    query = st.text_input("Ask a question about the PDF:")

    if query:
        results = vector_store.similarity_search(query, k=1)
        st.write("Answer:")
        st.write(results[0].page_content)

